//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoOculto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presente
    {
        public int Id { get; set; }
        public int id_Usuario { get; set; }
        public int id_Grupo { get; set; }
        public string Descricao { get; set; }
        public decimal ValorMaximo { get; set; }
        public decimal ValorMinimo { get; set; }
        public System.DateTime dttCadastro { get; set; }
    }
}
