//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoOculto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorteio
    {
        public int Id { get; set; }
        public int id_Usuario_Origem { get; set; }
        public Nullable<int> id_Usuario_Destino { get; set; }
        public int id_Grupo { get; set; }
        public System.DateTime dttCadastro { get; set; }
        public System.DateTime dttRevelacao { get; set; }
    }
}
