//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoOculto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string User { get; set; }
        public string Password { get; set; }
        public System.DateTime DttCriacao { get; set; }
        public string NomeCmp { get; set; }
        public bool Ativo { get; set; }
        public bool Administrador { get; set; }
        public int id_Grupo { get; set; }
    }
}
